/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface MedicineTraceabilityInterface extends Interface {
    getFunction(nameOrSignature: "batchExistsCheck" | "createBatch" | "getBatch" | "initiateTransfer" | "recallBatch" | "receiveTransfer" | "verifyBatch"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BatchCreated" | "Recalled" | "TransferInitiated" | "TransferReceived" | "Verified"): EventFragment;

    encodeFunctionData(functionFragment: 'batchExistsCheck', values: [string]): string;
encodeFunctionData(functionFragment: 'createBatch', values: [string]): string;
encodeFunctionData(functionFragment: 'getBatch', values: [string]): string;
encodeFunctionData(functionFragment: 'initiateTransfer', values: [string, AddressLike]): string;
encodeFunctionData(functionFragment: 'recallBatch', values: [string]): string;
encodeFunctionData(functionFragment: 'receiveTransfer', values: [string]): string;
encodeFunctionData(functionFragment: 'verifyBatch', values: [string]): string;

    decodeFunctionResult(functionFragment: 'batchExistsCheck', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initiateTransfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recallBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'receiveTransfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyBatch', data: BytesLike): Result;
  }

  
    export namespace BatchCreatedEvent {
      export type InputTuple = [batchId: string, manufacturer: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [batchId: string, manufacturer: string, timestamp: bigint];
      export interface OutputObject {batchId: string, manufacturer: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RecalledEvent {
      export type InputTuple = [batchId: string, manufacturer: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [batchId: string, manufacturer: string, timestamp: bigint];
      export interface OutputObject {batchId: string, manufacturer: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferInitiatedEvent {
      export type InputTuple = [batchId: string, from: AddressLike, to: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [batchId: string, from: string, to: string, timestamp: bigint];
      export interface OutputObject {batchId: string, from: string, to: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferReceivedEvent {
      export type InputTuple = [batchId: string, receiver: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [batchId: string, receiver: string, timestamp: bigint];
      export interface OutputObject {batchId: string, receiver: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VerifiedEvent {
      export type InputTuple = [batchId: string, verifier: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [batchId: string, verifier: string, timestamp: bigint];
      export interface OutputObject {batchId: string, verifier: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MedicineTraceability extends BaseContract {
    
    connect(runner?: ContractRunner | null): MedicineTraceability;
    waitForDeployment(): Promise<this>;

    interface: MedicineTraceabilityInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    batchExistsCheck: TypedContractMethod<
      [batchId: string, ],
      [boolean],
      'view'
    >
    

    
    createBatch: TypedContractMethod<
      [batchId: string, ],
      [void],
      'nonpayable'
    >
    

    
    getBatch: TypedContractMethod<
      [batchId: string, ],
      [[string, string, bigint] & {manufacturer: string, currentOwner: string, status: bigint }],
      'view'
    >
    

    
    initiateTransfer: TypedContractMethod<
      [batchId: string, to: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    recallBatch: TypedContractMethod<
      [batchId: string, ],
      [void],
      'nonpayable'
    >
    

    
    receiveTransfer: TypedContractMethod<
      [batchId: string, ],
      [void],
      'nonpayable'
    >
    

    
    verifyBatch: TypedContractMethod<
      [batchId: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'batchExistsCheck'): TypedContractMethod<
      [batchId: string, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'createBatch'): TypedContractMethod<
      [batchId: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getBatch'): TypedContractMethod<
      [batchId: string, ],
      [[string, string, bigint] & {manufacturer: string, currentOwner: string, status: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'initiateTransfer'): TypedContractMethod<
      [batchId: string, to: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'recallBatch'): TypedContractMethod<
      [batchId: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'receiveTransfer'): TypedContractMethod<
      [batchId: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifyBatch'): TypedContractMethod<
      [batchId: string, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'BatchCreated'): TypedContractEvent<BatchCreatedEvent.InputTuple, BatchCreatedEvent.OutputTuple, BatchCreatedEvent.OutputObject>;
getEvent(key: 'Recalled'): TypedContractEvent<RecalledEvent.InputTuple, RecalledEvent.OutputTuple, RecalledEvent.OutputObject>;
getEvent(key: 'TransferInitiated'): TypedContractEvent<TransferInitiatedEvent.InputTuple, TransferInitiatedEvent.OutputTuple, TransferInitiatedEvent.OutputObject>;
getEvent(key: 'TransferReceived'): TypedContractEvent<TransferReceivedEvent.InputTuple, TransferReceivedEvent.OutputTuple, TransferReceivedEvent.OutputObject>;
getEvent(key: 'Verified'): TypedContractEvent<VerifiedEvent.InputTuple, VerifiedEvent.OutputTuple, VerifiedEvent.OutputObject>;

    filters: {
      
      'BatchCreated(string,address,uint256)': TypedContractEvent<BatchCreatedEvent.InputTuple, BatchCreatedEvent.OutputTuple, BatchCreatedEvent.OutputObject>;
      BatchCreated: TypedContractEvent<BatchCreatedEvent.InputTuple, BatchCreatedEvent.OutputTuple, BatchCreatedEvent.OutputObject>;
    

      'Recalled(string,address,uint256)': TypedContractEvent<RecalledEvent.InputTuple, RecalledEvent.OutputTuple, RecalledEvent.OutputObject>;
      Recalled: TypedContractEvent<RecalledEvent.InputTuple, RecalledEvent.OutputTuple, RecalledEvent.OutputObject>;
    

      'TransferInitiated(string,address,address,uint256)': TypedContractEvent<TransferInitiatedEvent.InputTuple, TransferInitiatedEvent.OutputTuple, TransferInitiatedEvent.OutputObject>;
      TransferInitiated: TypedContractEvent<TransferInitiatedEvent.InputTuple, TransferInitiatedEvent.OutputTuple, TransferInitiatedEvent.OutputObject>;
    

      'TransferReceived(string,address,uint256)': TypedContractEvent<TransferReceivedEvent.InputTuple, TransferReceivedEvent.OutputTuple, TransferReceivedEvent.OutputObject>;
      TransferReceived: TypedContractEvent<TransferReceivedEvent.InputTuple, TransferReceivedEvent.OutputTuple, TransferReceivedEvent.OutputObject>;
    

      'Verified(string,address,uint256)': TypedContractEvent<VerifiedEvent.InputTuple, VerifiedEvent.OutputTuple, VerifiedEvent.OutputObject>;
      Verified: TypedContractEvent<VerifiedEvent.InputTuple, VerifiedEvent.OutputTuple, VerifiedEvent.OutputObject>;
    
    };
  }